### ISSUE TITLE
Multiplexing of request/response and publish/subscribe on the same channel

### ISSUE THREAD

**Issue by gianluca-venturini** [nutella-framework/nutella_lib.js#1]
A very interesting feature will be the possibility of multiplexing the same channel in both modality. This will enable the following pattern:
- Client get all the data on that channel with a request (the server always reply with the entire list to a request)
- Client subscribe to that channel in order to receive updates (if something change).

**Comment by tebemis** [comment]
That would be cool indeed. Let's do it since I think we are already very close on this one. We already separate `request` and `response` messages by marking them explicitly and by the fact that they have an `id` field. `handle_requests ` already ignores anything that is not marked as request/response. We just have to modify the `subscribe` to ignore the `request` and `response` messages. Sounds like a plan?

**Comment by tebemis** [comment]
Supported in [v0.3.0](https://github.com/nutella-framework/nutella_lib.js/releases/tag/v0.3.0)
